//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id { get; set; }
        public string customerName { get; set; }
        public string customerAddress { get; set; }
        public string customerPhone { get; set; }
        public System.DateTime bookingFrom { get; set; }
        public System.DateTime bookingTo { get; set; }
        public int noOfMembers { get; set; }
        public decimal totalAmount { get; set; }
        public int roomId { get; set; }
    
        public virtual rooms rooms { get; set; }
    }
}
