//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHotelManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HildurDatabaseEntities : DbContext
    {
        public HildurDatabaseEntities()
            : base("name=HildurDatabaseEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

  
        public virtual DbSet<bookingStatus> bookingStatus { get; set; }


        public virtual DbSet<roomTypes> roomTypes { get; set; }
        public virtual DbSet<booking> booking { get; set; }
        public virtual DbSet<rooms> rooms { get; set; }
    }
}