//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rooms()
        {
            this.booking = new HashSet<booking>();
        }
    
        public int id { get; set; }
        public string roomNumber { get; set; }
        public string roomImage { get; set; }
        public int roomTypeId { get; set; }
        public int roomPrice { get; set; }
        public int bookingStatusId { get; set; }
        public int roomCapacity { get; set; }
        public string roomDescription { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> booking { get; set; }
        public virtual bookingStatus bookingStatus { get; set; }
        public virtual roomTypes roomTypes { get; set; }
    }
}
